# Generated by Django 4.2.7 on 2024-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashbord', '0002_alter_dashbordmodel_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbordmodel',
            name='insight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dashbordmodel',
            name='title',
            field=models.TextField(),
        ),
    ]
