# Generated by Django 4.2.7 on 2024-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashbord', '0003_alter_dashbordmodel_insight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbordmodel',
            name='url',
            field=models.TextField(),
        ),
    ]
