# Generated by Django 4.2.7 on 2024-07-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashbord', '0004_alter_dashbordmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbordmodel',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashbordmodel',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashbordmodel',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
