# Generated by Django 4.2.7 on 2024-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydashbord', '0005_alter_dashbordmodel_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashbordmodel',
            name='source',
            field=models.TextField(),
        ),
    ]
